version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: repo
          params:
            depth: 1
  #- stage:
  #    - dockerfile:
  #        params:
  #          path: Dockerfile
  #          workdir: ${repo}
  #          build_args:
  #            GOPROXY: https://goproxy.cn
  #            HTTP_PROXY: ${{ configs.HTTP_PROXY }}
  #            HTTPS_PROXY: ${{ configs.HTTP_PROXY }}
  - stage:
      - release:
          params:
            dice_yml: ${repo}/dice.yml
  - stage:
      - dice:
          params:
            release_id: ${release:OUTPUT:releaseID}
